### ISSUE TITLE
Vocab add appears to be failing

### ISSUE THREAD

**Issue by abbistani** [lyrasis/collectionspace_migration_tools#30]
`$ thor vt:add --csv=~/LyrWrk/BPL/Location_Types_List.csv`

produces

```
Setting up for vocabulary term creation...
ERROR in CollectionspaceMigrationTools::Build::VocabHandler.call
MESSAGE:
/vocabularies GET
```

With the attached CSV
[Location_Types_List.csv](https://github.com/lyrasis/collectionspace_migration_tools/files/11274903/Location_Types_List.csv)

**Comment by kspurgin** [comment]
@abbistani -- I am unable to reproduce this!

I did notice that you enter the --csv option differently than me. 

When I do 

`thor vt:add --csv=~/data/mmm/mig/cspace/loansin_terms.csv`

I get an error, but it is different from yours: 

```
Setting up for vocabulary term creation...
No such file or directory @ rb_sysopen - ~/data/mmm/mig/cspace/loansin_terms.csv
```

When I do it without the `=`, it works: 

```
thor vt:add --csv ~/data/mmm/mig/cspace/loansin_terms.csv
Setting up for vocabulary term creation...
loanoutstatus / Credit line / success
loanoutstatus / Note / success
loanoutstatus / Original loan end / success
loanoutstatus / Agreement sent / success
loanoutstatus / Agreement received / success
loanoutstatus / Display begin / success
loanoutstatus / Display end / success
loanoutstatus / Approved / success
```

Could it be so simple? (probably not)

**Comment by abbistani** [comment]
Alas not.  I'll poke around and see if I can find something else that might be doing it.

**Comment by abbistani** [comment]
It was permissions.  Someone on the client side appears to have changed the permissions on my Brian account. Sigh.
